import tailwindcssAnimate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                /* ── Compass primitive scales (foundation Color page values) ── */
                primary: {
                    50: '#EBF1F0',
                    100: '#D1DFDD',
                    200: '#A8C2BE',
                    300: '#7AA29C',
                    400: '#427B72',
                    500: '#004D40',
                    600: '#002E26',
                    700: '#00231D',
                    800: '#001612',
                    900: '#000B09',
                    950: '#000403',
                    DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
                    foreground: 'hsl(var(--primary-foreground) / <alpha-value>)',
                },
                accent: {
                    50: '#FDF8E6',
                    100: '#FBEBBA',
                    200: '#F8D882',
                    300: '#F4C44A',
                    400: '#E6A514',
                    500: '#D4AF37',
                    600: '#BCA033',
                    700: '#96802A',
                    800: '#6A5B1E',
                    900: '#3D3411',
                    950: '#1A1607',
                    DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
                    foreground: 'hsl(var(--accent-foreground) / <alpha-value>)',
                },
                neutral: {
                    50: '#FAFAFA',
                    100: '#F4F4F5',
                    200: '#E5E7EB',
                    300: '#D1D5DA',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#5F5B5B',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#0F172A',
                    950: '#030712',
                },
                /* Petrol alias = primary (risk scale lives here too) */
                petrol: {
                    50: '#EBF1F0', 100: '#D1DFDD', 200: '#A8C2BE', 300: '#7AA29C',
                    400: '#427B72', 500: '#004D40', 600: '#002E26', 700: '#00231D',
                    800: '#001612', 900: '#000B09', 950: '#000403',
                },
                gold: {
                    50: '#FDF8E6', 100: '#FBEBBA', 200: '#F8D882', 300: '#F4C44A',
                    400: '#E6A514', 500: '#D4AF37', 600: '#BCA033', 700: '#96802A',
                    800: '#6A5B1E', 900: '#3D3411', 950: '#1A1607',
                },

                /* ── Compass semantic (CSS-variable backed, theme-aware) ── */
                brand: {
                    DEFAULT: 'rgb(var(--color-bg-brand) / <alpha-value>)',
                    light: 'rgb(var(--color-bg-brand-light) / <alpha-value>)',
                    /* Full-bleed brand panels that carry copy — see index.css. */
                    surface: 'rgb(var(--color-bg-brand-surface) / <alpha-value>)',
                },
                'brand-accent': {
                    DEFAULT: 'rgb(var(--color-bg-accent) / <alpha-value>)',
                    light: 'rgb(var(--color-bg-accent-light) / <alpha-value>)',
                },
                /* Translucent depth overlay — see index.css. Flips direction per theme. */
                elevate: 'rgb(var(--color-elevate) / <alpha-value>)',
                surface: {
                    DEFAULT: 'rgb(var(--color-bg-primary) / <alpha-value>)',
                    secondary: 'rgb(var(--color-bg-secondary) / <alpha-value>)',
                    tertiary: 'rgb(var(--color-bg-tertiary) / <alpha-value>)',
                    inverse: 'rgb(var(--color-bg-inverse) / <alpha-value>)',
                },
                fg: {
                    DEFAULT: 'rgb(var(--color-text-primary) / <alpha-value>)',
                    secondary: 'rgb(var(--color-text-secondary) / <alpha-value>)',
                    tertiary: 'rgb(var(--color-text-tertiary) / <alpha-value>)',
                    disabled: 'rgb(var(--color-text-disabled) / <alpha-value>)',
                    inverse: 'rgb(var(--color-text-inverse) / <alpha-value>)',
                    brand: 'rgb(var(--color-text-brand) / <alpha-value>)',
                    accent: 'rgb(var(--color-text-accent) / <alpha-value>)',
                    'accent-emphasis': 'rgb(var(--color-text-accent-emphasis) / <alpha-value>)',
                    'accent-strong': 'rgb(var(--color-text-accent-strong) / <alpha-value>)',
                    'on-brand': 'rgb(var(--color-text-on-brand) / <alpha-value>)',
                    'on-brand-accent': 'rgb(var(--color-text-on-brand-accent) / <alpha-value>)',
                    'on-accent': 'rgb(var(--color-text-on-accent) / <alpha-value>)',
                },
                stroke: {
                    DEFAULT: 'rgb(var(--color-border-default) / <alpha-value>)',
                    subtle: 'rgb(var(--color-border-subtle) / <alpha-value>)',
                    strong: 'rgb(var(--color-border-strong) / <alpha-value>)',
                    'strong-a11y': 'rgb(var(--color-border-strong-a11y) / <alpha-value>)',
                    input: 'rgb(var(--color-border-input) / <alpha-value>)',
                    brand: 'rgb(var(--color-border-brand) / <alpha-value>)',
                    accent: 'rgb(var(--color-border-accent) / <alpha-value>)',
                    focus: 'rgb(var(--color-border-focus) / <alpha-value>)',
                },
                risk: {
                    low: 'rgb(var(--color-risk-low) / <alpha-value>)',
                    medium: 'rgb(var(--color-risk-medium) / <alpha-value>)',
                    high: 'rgb(var(--color-risk-high) / <alpha-value>)',
                    critical: 'rgb(var(--color-risk-critical) / <alpha-value>)',
                    'low-bg': 'rgb(var(--color-risk-low-bg) / <alpha-value>)',
                    'medium-bg': 'rgb(var(--color-risk-medium-bg) / <alpha-value>)',
                    'high-bg': 'rgb(var(--color-risk-high-bg) / <alpha-value>)',
                    'critical-bg': 'rgb(var(--color-risk-critical-bg) / <alpha-value>)',
                    /* Foreground for the soft variant — text ON the *-bg tint. */
                    'on-low': 'rgb(var(--color-risk-text-on-low) / <alpha-value>)',
                    'on-medium': 'rgb(var(--color-risk-text-on-medium) / <alpha-value>)',
                    'on-high': 'rgb(var(--color-risk-text-on-high) / <alpha-value>)',
                    'on-critical': 'rgb(var(--color-risk-text-on-critical) / <alpha-value>)',
                },

                /* ── Status (interim — refine vs Compass Color page) ── */
                success: {
                    bg: '#D1FAE5', text: '#2C6B5C',
                    50: '#F3F9F8', 100: '#D4EAE5', 200: '#A7D6CB', 300: '#76C1B0', 400: '#4DAF99',
                    500: '#3C8C7A', 600: '#347C6B', 700: '#2C6B5C', 800: '#205146', 900: '#153830', 950: '#0A1C18',
                },
                warning: {
                    bg: '#FEF3C7', text: '#876B1F',
                    50: '#FAF8F2', 100: '#F0E9D6', 200: '#E3D4AE', 300: '#D7BF81', 400: '#CDAE5B',
                    500: '#C59E38', 600: '#AA8B2C', 700: '#8E7321', 800: '#695218', 900: '#463710', 950: '#201907',
                },
                error: {
                    bg: '#FBE9E9', text: '#8A3B3B',
                    50: '#F9F3F3', 100: '#EDDADA', 200: '#DDB8B8', 300: '#CD9292', 400: '#C07171',
                    500: '#B55353', 600: '#A14545', 700: '#8A3B3B', 800: '#662929', 900: '#431919', 950: '#1C0A0A',
                },
                info: {
                    bg: '#E5EDFD', text: '#1E4FB0',
                    50: '#F0F4FD', 100: '#D2DFF9', 200: '#A8C2F5', 300: '#7AA2F0', 400: '#5387ED',
                    500: '#2F6FEB', 600: '#1C5BD8', 700: '#1E4FB0', 800: '#103686', 900: '#062159', 950: '#010D26',
                },

                /* ── shadcn CSS variable colors (back-compat) ── */
                background: 'hsl(var(--background) / <alpha-value>)',
                foreground: 'hsl(var(--foreground) / <alpha-value>)',
                card: { DEFAULT: 'hsl(var(--card) / <alpha-value>)', foreground: 'hsl(var(--card-foreground) / <alpha-value>)' },
                popover: { DEFAULT: 'hsl(var(--popover) / <alpha-value>)', foreground: 'hsl(var(--popover-foreground) / <alpha-value>)' },
                secondary: { DEFAULT: 'hsl(var(--secondary) / <alpha-value>)', foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)' },
                muted: { DEFAULT: 'hsl(var(--muted) / <alpha-value>)', foreground: 'hsl(var(--muted-foreground) / <alpha-value>)' },
                destructive: { DEFAULT: 'hsl(var(--destructive) / <alpha-value>)', foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)' },
                border: 'hsl(var(--border) / <alpha-value>)',
                input: 'hsl(var(--input) / <alpha-value>)',
                ring: 'hsl(var(--ring) / <alpha-value>)',
                'warm-grey': '#EFE8E8',
                'soft-blue': '#C3DDDC',
                chart: {
                    1: 'hsl(var(--chart-1) / <alpha-value>)',
                    2: 'hsl(var(--chart-2) / <alpha-value>)',
                    3: 'hsl(var(--chart-3) / <alpha-value>)',
                    4: 'hsl(var(--chart-4) / <alpha-value>)',
                    5: 'hsl(var(--chart-5) / <alpha-value>)',
                },
                sidebar: {
                    DEFAULT: 'hsl(var(--sidebar-background) / <alpha-value>)',
                    foreground: 'hsl(var(--sidebar-foreground) / <alpha-value>)',
                    primary: 'hsl(var(--sidebar-primary) / <alpha-value>)',
                    'primary-foreground': 'hsl(var(--sidebar-primary-foreground) / <alpha-value>)',
                    accent: 'hsl(var(--sidebar-accent) / <alpha-value>)',
                    'accent-foreground': 'hsl(var(--sidebar-accent-foreground) / <alpha-value>)',
                    border: 'hsl(var(--sidebar-border) / <alpha-value>)',
                    ring: 'hsl(var(--sidebar-ring) / <alpha-value>)',
                },
            },
            screens: {
                'sm': '600px',
                'md': '768px',
                'lg': '1024px',
                'xl': '1440px',
                '2xl': '1920px',
                /* legacy device aliases (kept) */
                'mobile-m': '375px',
                'mobile-l': '414px',
                'tablet': '768px',
                'desktop-s': '1024px',
                'desktop-m': '1280px',
                'desktop-l': '1440px',
                'desktop-xl': '1920px',
            },
            maxWidth: {
                'container-sm': '600px',
                'container-md': '768px',
                'container-lg': '1024px',
                'container-xl': '1200px',
                'container-2xl': '1440px',
            },
            fontFamily: {
                sans: ['"Inter"', 'system-ui', 'sans-serif'],
                serif: ['"IBM Plex Serif"', 'Georgia', 'serif'],
            },
            fontSize: {
                /* Compass type scale (px → rem) */
                'display-2xl': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
                'display-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
                'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
                'display-md': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.005em' }],
                'display-sm': ['2.25rem', { lineHeight: '1.2' }],
                'h1': ['2rem', { lineHeight: '1.3', letterSpacing: '-0.005em' }],
                'h2': ['1.5rem', { lineHeight: '1.3' }],
                'h3': ['1.25rem', { lineHeight: '1.3' }],
                'h4': ['1.125rem', { lineHeight: '1.4' }],
                'h5': ['1rem', { lineHeight: '1.4' }],
                'h6': ['0.875rem', { lineHeight: '1.4' }],
                'body-lg': ['1.125rem', { lineHeight: '1.6' }],
                'body': ['1rem', { lineHeight: '1.6' }],
                'body-sm': ['0.875rem', { lineHeight: '1.6' }],
                'body-xs': ['0.8125rem', { lineHeight: '1.6' }],
                'label': ['0.875rem', { lineHeight: '1.4' }],
                'ui-small': ['0.875rem', { lineHeight: '1.4' }],
                'caption': ['0.75rem', { lineHeight: '1.45', letterSpacing: '0.01em' }],
                'eyebrow': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.14em' }],
            },
            spacing: {
                /* 4px-based scale (kept for back-compat with existing components).
                   Compass spacing/N values are all reachable here; do NOT remap the
                   numeric utility scale to Compass spacing/N — different numbering. */
                '1': '4px',
                '2': '8px',
                '3': '12px',
                '4': '16px',
                '5': '20px',
                '6': '24px',
                '7': '32px',
                '8': '40px',
                '10': '64px',
                '12': '96px',
            },
            borderRadius: {
                'none': '0px',
                'xs': '2px',
                'sm': '4px',
                'md': '6px',
                'lg': '8px',
                'xl': '10px',
                '2xl': '12px',
                '3xl': '16px',
                'pill': '9999px',
                'full': '9999px',
            },
            borderWidth: {
                DEFAULT: '1px',
                'none': '0px',
                'sm': '1px',
                'md': '2px',
                'lg': '4px',
                /* legacy aliases */
                'thin': '1px',
                'medium': '2px',
                'thick': '4px',
            },
            boxShadow: {
                'xs': 'var(--shadow-xs)',
                'sm': 'var(--shadow-sm)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
                'xl': 'var(--shadow-xl)',
                '2xl': 'var(--shadow-2xl)',
                'inner': 'var(--shadow-inner)',
            },
            ringColor: {
                focus: 'rgb(var(--color-border-focus) / <alpha-value>)',
            },
        },
    },
    plugins: [tailwindcssAnimate],
}
