import tailwindcssAnimate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                /* ── Compass primitive scales (foundation Color page values) ── */
                primary: {
                    50: '#EBF1F0',
                    100: '#D1DFDD',
                    200: '#A8C2BE',
                    300: '#7AA29C',
                    400: '#427B72',
                    500: '#004D40',
                    600: '#002E26',
                    700: '#00231D',
                    800: '#001612',
                    900: '#000B09',
                    950: '#000403',
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                accent: {
                    50: '#FDF8E6',
                    100: '#FBEBBA',
                    200: '#F8D882',
                    300: '#F4C44A',
                    400: '#E6A514',
                    500: '#D4AF37',
                    600: '#BCA033',
                    700: '#96802A',
                    800: '#6A5B1E',
                    900: '#3D3411',
                    950: '#1A1607',
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                neutral: {
                    50: '#FAFAFA',
                    100: '#F4F4F5',
                    200: '#E5E7EB',
                    300: '#D1D5DA',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#5F5B5B',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#0F172A',
                    950: '#030712',
                },
                /* Petrol alias = primary (risk scale lives here too) */
                petrol: {
                    50: '#EBF1F0', 100: '#D1DFDD', 200: '#A8C2BE', 300: '#7AA29C',
                    400: '#427B72', 500: '#004D40', 600: '#002E26', 700: '#00231D',
                    800: '#001612', 900: '#000B09', 950: '#000403',
                },
                gold: {
                    50: '#FDF8E6', 100: '#FBEBBA', 200: '#F8D882', 300: '#F4C44A',
                    400: '#E6A514', 500: '#D4AF37', 600: '#BCA033', 700: '#96802A',
                    800: '#6A5B1E', 900: '#3D3411', 950: '#1A1607',
                },

                /* ── Compass semantic (CSS-variable backed, theme-aware) ── */
                brand: {
                    DEFAULT: 'var(--color-bg-brand)',
                    light: 'var(--color-bg-brand-light)',
                },
                'brand-accent': {
                    DEFAULT: 'var(--color-bg-accent)',
                    light: 'var(--color-bg-accent-light)',
                },
                surface: {
                    DEFAULT: 'var(--color-bg-primary)',
                    secondary: 'var(--color-bg-secondary)',
                    tertiary: 'var(--color-bg-tertiary)',
                    inverse: 'var(--color-bg-inverse)',
                },
                fg: {
                    DEFAULT: 'var(--color-text-primary)',
                    secondary: 'var(--color-text-secondary)',
                    tertiary: 'var(--color-text-tertiary)',
                    disabled: 'var(--color-text-disabled)',
                    inverse: 'var(--color-text-inverse)',
                    brand: 'var(--color-text-brand)',
                    accent: 'var(--color-text-accent)',
                    'accent-emphasis': 'var(--color-text-accent-emphasis)',
                    'on-brand': 'var(--color-text-on-brand)',
                    'on-accent': 'var(--color-text-on-accent)',
                },
                stroke: {
                    DEFAULT: 'var(--color-border-default)',
                    subtle: 'var(--color-border-subtle)',
                    strong: 'var(--color-border-strong)',
                    'strong-a11y': 'var(--color-border-strong-a11y)',
                    input: 'var(--color-border-input)',
                    brand: 'var(--color-border-brand)',
                    accent: 'var(--color-border-accent)',
                    focus: 'var(--color-border-focus)',
                },
                risk: {
                    low: 'var(--color-risk-low)',
                    medium: 'var(--color-risk-medium)',
                    high: 'var(--color-risk-high)',
                    critical: 'var(--color-risk-critical)',
                    'low-bg': 'var(--color-risk-low-bg)',
                    'medium-bg': 'var(--color-risk-medium-bg)',
                    'high-bg': 'var(--color-risk-high-bg)',
                    'critical-bg': 'var(--color-risk-critical-bg)',
                },

                /* ── Status (interim — refine vs Compass Color page) ── */
                success: { bg: '#D1FAE5', 500: '#3C8C7A', 700: '#2C6B5C' },
                warning: { bg: '#FEF3C7', 500: '#C59E38', 700: '#8E7321' },
                error: { bg: '#FBE9E9', 500: '#B55353', 700: '#8A3B3B' },
                info: { bg: '#E5EDFD', 500: '#2F6FEB', 700: '#1E4FB0' },

                /* ── shadcn CSS variable colors (back-compat) ── */
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
                popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
                secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
                muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
                destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                'warm-grey': '#EFE8E8',
                'soft-blue': '#C3DDDC',
                chart: {
                    1: 'hsl(var(--chart-1))',
                    2: 'hsl(var(--chart-2))',
                    3: 'hsl(var(--chart-3))',
                    4: 'hsl(var(--chart-4))',
                    5: 'hsl(var(--chart-5))',
                },
                sidebar: {
                    DEFAULT: 'hsl(var(--sidebar-background))',
                    foreground: 'hsl(var(--sidebar-foreground))',
                    primary: 'hsl(var(--sidebar-primary))',
                    'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
                    accent: 'hsl(var(--sidebar-accent))',
                    'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
                    border: 'hsl(var(--sidebar-border))',
                    ring: 'hsl(var(--sidebar-ring))',
                },
            },
            screens: {
                'sm': '600px',
                'md': '768px',
                'lg': '1024px',
                'xl': '1440px',
                '2xl': '1920px',
                /* legacy device aliases (kept) */
                'mobile-m': '375px',
                'mobile-l': '414px',
                'tablet': '768px',
                'desktop-s': '1024px',
                'desktop-m': '1280px',
                'desktop-l': '1440px',
                'desktop-xl': '1920px',
            },
            maxWidth: {
                'container-sm': '600px',
                'container-md': '768px',
                'container-lg': '1024px',
                'container-xl': '1200px',
                'container-2xl': '1440px',
            },
            fontFamily: {
                sans: ['"Inter"', 'system-ui', 'sans-serif'],
                serif: ['"IBM Plex Serif"', 'Georgia', 'serif'],
            },
            fontSize: {
                /* Compass type scale (px → rem) */
                'display-2xl': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
                'display-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
                'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
                'display-md': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.005em' }],
                'display-sm': ['2.25rem', { lineHeight: '1.2' }],
                'h1': ['2rem', { lineHeight: '1.3', letterSpacing: '-0.005em' }],
                'h2': ['1.5rem', { lineHeight: '1.3' }],
                'h3': ['1.25rem', { lineHeight: '1.3' }],
                'h4': ['1.125rem', { lineHeight: '1.4' }],
                'h5': ['1rem', { lineHeight: '1.4' }],
                'h6': ['0.875rem', { lineHeight: '1.4' }],
                'body-lg': ['1.125rem', { lineHeight: '1.6' }],
                'body': ['1rem', { lineHeight: '1.6' }],
                'body-sm': ['0.875rem', { lineHeight: '1.6' }],
                'body-xs': ['0.8125rem', { lineHeight: '1.6' }],
                'label': ['0.875rem', { lineHeight: '1.4' }],
                'ui-small': ['0.875rem', { lineHeight: '1.4' }],
                'caption': ['0.75rem', { lineHeight: '1.45', letterSpacing: '0.01em' }],
                'eyebrow': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.14em' }],
            },
            spacing: {
                /* 4px-based scale (kept for back-compat with existing components).
                   Compass spacing/N values are all reachable here; do NOT remap the
                   numeric utility scale to Compass spacing/N — different numbering. */
                '1': '4px',
                '2': '8px',
                '3': '12px',
                '4': '16px',
                '5': '20px',
                '6': '24px',
                '7': '32px',
                '8': '40px',
                '10': '64px',
                '12': '96px',
            },
            borderRadius: {
                'none': '0px',
                'xs': '2px',
                'sm': '4px',
                'md': '6px',
                'lg': '8px',
                'xl': '10px',
                '2xl': '12px',
                '3xl': '16px',
                'pill': '9999px',
                'full': '9999px',
            },
            borderWidth: {
                DEFAULT: '1px',
                'none': '0px',
                'sm': '1px',
                'md': '2px',
                'lg': '4px',
                /* legacy aliases */
                'thin': '1px',
                'medium': '2px',
                'thick': '4px',
            },
            boxShadow: {
                'xs': 'var(--shadow-xs)',
                'sm': 'var(--shadow-sm)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
                'xl': 'var(--shadow-xl)',
                '2xl': 'var(--shadow-2xl)',
                'inner': 'var(--shadow-inner)',
            },
            ringColor: {
                focus: 'var(--color-border-focus)',
            },
        },
    },
    plugins: [tailwindcssAnimate],
}
