/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                /* ── Brand Color Palette (existing) ── */
                primary: {
                    50: '#E8F5E9',
                    100: '#C8E6C9',
                    200: '#A5D6A7',
                    300: '#81C784',
                    400: '#66BB6A',
                    500: '#004D40',
                    600: '#003E33',
                    700: '#002E26',
                    800: '#001F1A',
                    900: '#000F0D',
                    950: '#000504',
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                accent: {
                    50: '#FDF8E6',
                    100: '#FBEBBA',
                    200: '#F8D882',
                    300: '#F4C44A',
                    400: '#E6A514',
                    500: '#D4AF37',
                    600: '#BCA033',
                    700: '#8E7321',
                    800: '#69551A',
                    900: '#4D3E14',
                    950: '#2F260A',
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                neutral: {
                    50: '#FAFAFA', 
                    100: '#F4F4F5',
                    200: '#E5E7EB',
                    300: '#D4D4D8',
                    400: '#A1A1AA',
                    500: '#71717A',
                    600: '#5F5A5A',
                    700: '#3F3F46',
                    800: '#27272A',
                    900: '#0F172A',
                    950: '#18181B',
                },
                'brand-surface': '#E8F5E9',
                'warm-grey': '#EFE8E8',
                'soft-blue': '#C3DDDC',
                success: {
                    bg: '#D1FAE5',
                    500: '#10B981',
                    700: '#047857',
                },
                warning: {
                    bg: '#FEF3C7',
                    500: '#F59E0B',
                    700: '#B45309',
                },
                error: {
                    bg: '#FEE2E2',
                    500: '#EF4444',
                    700: '#B91C1C',
                },

                /* ── shadcn CSS Variable Colors ── */
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                surface: '#FFFFFF',
                chart: {
                    1: 'hsl(var(--chart-1))',
                    2: 'hsl(var(--chart-2))',
                    3: 'hsl(var(--chart-3))',
                    4: 'hsl(var(--chart-4))',
                    5: 'hsl(var(--chart-5))',
                },
                sidebar: {
                    DEFAULT: 'hsl(var(--sidebar-background))',
                    foreground: 'hsl(var(--sidebar-foreground))',
                    primary: 'hsl(var(--sidebar-primary))',
                    'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
                    accent: 'hsl(var(--sidebar-accent))',
                    'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
                    border: 'hsl(var(--sidebar-border))',
                    ring: 'hsl(var(--sidebar-ring))',
                },
            },
            screens: {
                'sm': '320px',
                'mobile-m': '375px',
                'mobile-l': '414px',
                'tablet': '768px',
                'desktop-s': '1024px',
                'desktop-m': '1280px',
                'desktop-l': '1440px',
                'desktop-xl': '1920px',
            },
            fontFamily: {
                sans: ['"Inter"', 'sans-serif'],
                serif: ['"IBM Plex Serif"', 'serif'],
            },
            fontSize: {
                'display': ['3.5rem', { lineHeight: '1.2' }],
                'h1': ['2.25rem', { lineHeight: '1.2' }],
                'h2': ['1.75rem', { lineHeight: '1.2' }],
                'h3': ['1.25rem', { lineHeight: '1.2' }],
                'body': ['1rem', { lineHeight: '1.6' }],
                'ui-small': ['0.875rem', { lineHeight: '1.4' }],
                'caption': ['0.875rem', { letterSpacing: '0.04em', lineHeight: '1.4' }],
            },
            spacing: {
                '1': '4px',
                '2': '8px',
                '3': '12px',
                '4': '16px',
                '5': '20px',
                '6': '24px',
                '7': '32px',
                '8': '40px',
                '10': '64px',
                '12': '96px',
            },
            borderRadius: {
                'xs': '2px',
                'sm': '4px',
                'md': '8px',
                'lg': 'var(--radius)',
                'xl': '16px',
                'pill': '9999px',
            },
            borderWidth: {
                'thin': '1px',
                'medium': '2px',
                'thick': '3px',
                DEFAULT: '1px',
            },
            boxShadow: {
                'xs': '0px 1px 2px rgba(0,0,0,0.04)',
                'sm': '0px 2px 6px rgba(0,0,0,0.06)',
                'md': '0px 6px 16px rgba(0,0,0,0.08)',
                'lg': '0px 12px 32px rgba(0,0,0,0.10)',
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}
