import { CountryCode } from './country-profile';
import { IndustryType, BusinessModel } from './business-modifier';
import { generateRelevantSubdomains } from './generator';

/**
 * Formats the Subdomains generated by the Engine into the exact shape required
 * by the Frontend UI Wizard.
 */
export function getWizardSubcategories(context: {
    countries: CountryCode[];
    industry?: IndustryType;
    businessModel?: BusinessModel;
}) {
    return generateRelevantSubdomains(context);
}
